[server]
port = 8080

[bot]
image = { name = "mc-botnet-bot", restart = "Never", pull_policy = "Never" }
local.exec = "bun"
local.args = ["/home/bakane/Projects/mc-botnet-bot/dist/index.js"]

[grpc]
port = 8081
