[server]
port = 8080

[runner]
type = "local"

[runner.local]
exec = "bun"
args = ["/home/bakane/Projects/mc-botnet-bot/dist/index.js"]

[runner.kubernetes]
image = { name = "mc-botnet-bot", restart = "Never", pull_policy = "Never" }

[grpc]
port = 8081
