jwt.base64 = false
jwt.secret = "sigma"

[server]
port = 8080

[runner]
type = "local"

[runner.local]
cmd = "bun"
args = ["/home/bakane/Projects/mc-botnet/bot/dist/index.js"]

[runner.kubernetes]
image = { name = "mc-botnet-bot", restart = "Never", pull_policy = "Never" }

[grpc]
port = 8081

[database]
driver = "sqlite3"
url = "db.sqlite"
